spring:
  application:
    name: product-service # Mikroservis adı
  config:
    import: "configserver:" # Config Server'dan konfigürasyonları al
  cloud:
    config:
      uri: http://config-server:8888 # Config Server URL
      fail-fast: true # Bağlantı hatası durumunda uygulama başarısız olsun
