server:
  port: 8761
spring:
  application:
    name: eureka-server
  config:
    import: "configserver:" # Config Server'dan konfigürasyonları al
  cloud:
    config:
     uri: http://localhost:8888 # Config Server URL
     fail-fast: true # Bağlantı hatası durumunda uygulama başarısız olsun
