spring:
  application:
    name: apigateway-service
  config:
    import: "configserver:" # Config Server'dan konfigürasyonları al
  cloud:
    config:
      uri: http://localhost:8888 # Config Server URL
      fail-fast: true # Bağlantı hatası durumunda uygulama başarısız olsun
